#cloud-config
ssh_authorized_keys:
  - "${user_pubkey}"
coreos:
  locksmith:
  update:
    reboot-strategy: "${reboot_strategy}"
  units:
    - name: set-timezone.service
      enable: true
      content: |
        [Unit]
        Description=Set the time zone
        [Service]
        ExecStart=/usr/bin/timedatectl set-timezone UTC
        RemainAfterExit=yes
        Type=oneshot
        [Install]
        WantedBy=multi-user.target
    - name: networkd-restart.service
      command: start
      enable: true
      content: |
        [Unit]
        Description=Restart systemd-networkd to be sure we are using correct network settings
        [Service]
        Type=oneshot
        ExecStart=/usr/usr/bin/env bash -c 'systemctl restart systemd-networkd'
write_files:
  #ves
  - path: /etc/hosts
    content: ${hosts_context}
    permissions: 0644
    owner: root
    encoding: b64
  - path: /etc/vpm/config.yaml
    permissions: 0644
    owner: root
    encoding: b64
    content: ${vp_manager_context}
  - path: /etc/default/vpm
    content: ${vp_manager_environment_context}
    permissions: 0644
    owner: root
    encoding: b64
#  - path: "/etc/systemd/timesyncd.conf"
#   permissions: 0420
#   owner: root
#   content: |
#     [Time]
#     NTP=${ntp_servers}

